Fix registration bugs, update input design, and improve validation logic
platformplatform/PlatformPlatform pull request #543
Opened 2024-07-21 19:08 UTC by tjementum

### Summary & Motivation

Fix a bug in account registration where form state is lost, and address an issue where validation errors were not shown to users. Downgrading to React 18 Canary fixes this, as these bugs were related to React 19 Canary - Waiting for React Aria Components to catch up.

Restructure frontend pages to use a shared layout and move out components from pages / routing and into shared ui for a clearer seperation of concerns.
Update the design of input fields to ensure they are all the same height.

Remove client-side validation and disable browser native validation that duplicates server-side validation to ease maintainability and provide a clear seperation of responsibility between client and server validation.

Change the Account Registration start endpoint to return the `AccountRegistrationId` and expiration data in the response body, simplifying the frontend and allowing central control of the expiration time.

Add "is subdomain" check in the register page and illustrated messages for better user experience.

### Checklist

- [x] I have added a Label to the pull-request
- [x] I have added tests, and done manual regression tests
- [x] I have updated the documentation, if necessary

2024-07-21 21:24 UTC, raix requested changes
Let's not merge this for now - it's not solving the underlying issue of why things working suddenly stopped working.

2024-07-22 15:53 UTC, tjementum commented
> Let's not merge this for now - it's not solving the underlying issue of why things working suddenly stopped working.

I've have never seen errors in the UI. And losing form data has been a problem since we upgraded to React 19 Canary :)

2024-07-23 15:59 UTC, raix reviewed
Added a few notes - mostly to myself, will fix comments and merge

2024-07-23 15:59 UTC, raix commented on application/package.json
> +    "@types/react-dom": "^18.2.25",
I want to test the latest RAC instead of Downgrading React

2024-07-23 15:59 UTC, raix commented on application/shared-webapp/build/react-env.d.ts
> +/// <reference types="react/canary" />
Note to self: Remove

2024-07-23 15:59 UTC, raix commented on application/account-management/WebApp/pages/login/index.tsx
> +            </TextField>
Input props can be moved to TextField making the code less nested

2024-07-23 15:59 UTC, raix commented on application/account-management/WebApp/pages/login/index.tsx
> +            className="flex w-full max-w-sm flex-col items-center gap-4 space-y-3 px-6 pt-8 pb-4"
add `validationBehavior="aria"` to disable browser/native validation

2024-07-23 15:59 UTC, raix commented on application/account-management/WebApp/pages/register/verify/index.tsx
> +    <Form action={action} validationErrors={state.errors} className="w-full max-w-sm space-y-3">
add `validationBehavior="aria"` to disable browser/native validation

2024-07-24 06:33 UTC, raix approved these changes

2024-07-24 06:33 UTC, merged