Fix pull-platformplatform-changes on Windows
platformplatform/PlatformPlatform pull request #655
Opened 2024-12-30 14:18 UTC by thiagolunardi

### Summary & Motivation

While running on Windows, the `pp pull-platform platform-changes` fails because it couldn't find the `npm` command, which is not an executable file.

This fix searches for the precise command location while running on Windows OS using the `.exe` and `.cmd` extensions.

### Checklist

- [ ] I have added a Label to the pull-request
- [ ] I have added tests, and done manual regression tests
- [ ] I have updated the documentation, if necessary

2024-12-30 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/platformplatform/PlatformPlatform?pullRequest=655) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/platformplatform/PlatformPlatform?pullRequest=655) before we can accept your contribution.<br/><hr/>**Thiago Lunardi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/platformplatform/PlatformPlatform?pullRequest=655) it.</sub>

2025-01-02 20:57 UTC, tjementum requested changes
Hi Tiago

Thanks for the pull request, and sorry for the late reply. I get an exception on my Mac when running this, and I had to debug to find out what was wrong. It turns out this is because the PATH environment variable on Linux and macOS is split using `:` and not `;` like on Windows.

I made a comment and a suggested fix, but I will have to test that this did not break anything else. I don't have tests for the Developer CLI.

Also, I _always rebase branches_ before merging to main, and I _never merge main into a feature branch_. Please rebase your changes and squash everything, including my suggested change, into a single commit, and then force push the branch to your repository.

2025-01-02 20:57 UTC, tjementum commented on developer-cli/Utilities/ProcessHelper.cs
> +        foreach (var directory in pathVariable?.Split(';') ?? [])
@thiagolunardi The logic here here fails because on Mac and Linux `:` is used as path separator and not `;`.

I've tried this code and it seems to work... but I have to test that this did not break any other tings:

```C#
var pathVariable = Environment.GetEnvironmentVariable("PATH");
if (pathVariable == null) return null;

var separator = OperatingSystem.IsWindows() ? ';' : ':';
foreach (var directory in pathVariable.Split(separator))
{
    ...
}
```

2025-01-02 20:57 UTC, tjementum commented on developer-cli/Utilities/ProcessHelper.cs
> +        Debug.Assert(!string.IsNullOrWhiteSpace(command));
Please remove this line. I don't use `Debug.Assert()` anywhere else, so for now, I prefer not to change this.

2025-01-02 20:58 UTC, tjementum commented on developer-cli/Utilities/ProcessHelper.cs
> +        string[] commandFormats = OperatingSystem.IsWindows() ? ["{0}.exe", "{0}.cmd"] : ["{0}"];
```suggestion
        var commandFormats = OperatingSystem.IsWindows() ? new[] { "{0}.exe", "{0}.cmd" } : new[] { "{0}" };
```

You can run JetBrains code clean up and it will change `string[]` to `var`.

2025-01-04 12:47 UTC, thiagolunardi commented
Hi @tjementum 

I can try adding a test project to it and putting together a workflow to test this functionality initially. I can run it on Windows, Linux, and Mac. For example, I can run `npm—v` and expect to get its version across all platforms.

```csharp
public static class ProcessHelperTests
{
    public class StartProcessTests 
    {
        [Theory]
        [InlineData("npm -v")
        public void RequestVersion_ShouldReturnValidSemver(string command)
        {
                // Act
                var output = ProcessHelper.StartProcess(
                    command,
                    redirectOutput: true,
                    throwOnError: true);

                // Assert
                Assert.True(Version.TryParse(output, out _));
        }
    }
}
``` 

For that, I will need to make a tiny move and change the directory structure to look like this:
```bash
.
.
├─ development-cli       # Contains the development CLI source code
│  ├─ cli                # A .NET CLI tool for automating common developer tasks
│  ├─ tests              # Tests for the CLI
```

Do you think it makes sense?

2025-01-07 12:43 UTC, tjementum approved these changes
I've made the requested changes and force pushed them.

2025-01-07 12:50 UTC, merged